version: "3.9"
services:
  model_api:
    build: .
    container_name: model_api
    command: python3 app/run_server.py  # gunicorn --bind=0.0.0.0:8180 --chdir app run_server:app
    restart: unless-stopped
    environment:
      FLASK_SERVER_PORT: 8180
    ports:
     - "8180:8180"
    volumes:
      - /app/models
